# Generated by Django 2.2.12 on 2023-07-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
