# Generated by Django 2.2.12 on 2023-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField()),
                ('start_date', models.DateField()),
                ('and_date', models.DateField()),
                ('grade', models.TextField()),
            ],
        ),
    ]
