# Generated by Django 2.2.12 on 2023-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('short_description', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
