# Generated by Django 2.2.12 on 2023-07-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_personalinfo_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='last_name',
        ),
    ]
