# Generated by Django 2.2.12 on 2023-07-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='and_date',
            new_name='end_date',
        ),
    ]
