# Generated by Django 2.2.12 on 2023-07-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20230706_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
