# Generated by Django 4.2.4 on 2023-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_sociallink_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cours_name',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='courses',
            name='program',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='courses',
            name='program_name',
            field=models.TextField(max_length=60),
        ),
    ]
