# Generated by Django 4.2.4 on 2023-08-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_courses_cours_name_alter_courses_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_discription',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
