# Generated by Django 2.2.12 on 2023-07-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
    ]
