# Generated by Django 2.2.12 on 2023-07-10 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20230709_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.TextField(max_length=70)),
                ('linkdin', models.TextField(max_length=70)),
                ('facebook', models.TextField(max_length=70)),
                ('instagram', models.TextField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position_name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
