# Generated by Django 2.2.12 on 2023-07-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
