# Generated by Django 2.2.12 on 2023-07-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_experience_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('link_name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
