# Generated by Django 2.2.12 on 2023-07-10 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20230710_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('city', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=30)),
                ('freelance', models.CharField(max_length=30)),
            ],
        ),
    ]
