# Generated by Django 2.2.12 on 2023-07-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20230711_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('job_position', models.CharField(max_length=40)),
                ('opinion', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fact',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
