# Generated by Django 2.2.12 on 2023-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20230711_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField(max_length=40)),
                ('program_name', models.TextField(max_length=40)),
                ('cours_name', models.TextField(max_length=40)),
            ],
        ),
    ]
