# Generated by Django 2.2.12 on 2023-07-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_info',
            new_name='PersonalInfo',
        ),
    ]
